---
title: "Erdbeben Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
# function to check if package is present
install_if_not_present <- function(pkg_name){
  if(!requireNamespace(pkg_name, quietly = TRUE)){
    install.packages(pkg_name)
  }
}

install_if_not_present("tidyverse")
install_if_not_present("geojsonR")
install_if_not_present("jsonlite")
install_if_not_present("lubridate")
install_if_not_present("leaflet")
install_if_not_present("flexdashboard")
install_if_not_present("shiny")

library(tidyverse)
library(geojsonR)
library(jsonlite)
library(lubridate)
library(leaflet)
library(flexdashboard)
library(shiny)

# create variables for different periodes
past_day <- "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson"
past_week <- "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_week.geojson"
past_month <- "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_month.geojson"

pipeline <- function(geojson_file) {

      # read data from website
      dump <- Dump_From_GeoJson(geojson_file)
      
      # convert to JSON
      js <- fromJSON(dump)
      
      # extract features
      features <- js$features
      
      # extract coordinates
      geometry <- features$geometry
      coordinates <- geometry$coordinates
      coordinates <- do.call(rbind, coordinates)
      colnames(coordinates) <- c("lon", "lat", "depth")
      
      # extract properties into a dataframe
      properties <- cbind(features$properties, coordinates)
      
      properties <- properties %>% select(mag, place, time, status, updated, type, lon, lat, depth, tsunami, sig, code)
      
      # convert columns time and updated into datetime
      basedate <- as.POSIXct("1970-01-01 00:00:00", tz = "UTC")
      properties <- properties %>% 
        mutate(time = basedate + (time/ 1000)) %>% 
        mutate(updated = basedate + (updated/1000))
      
      # only accept values in the permitted range
      properties <- properties %>% 
        filter(between(lon, -180, 180),
               between(lat, -90, 90),
               between(depth, 0, 1000),
               between(mag, 5, 10))
      
      # drop NA for mandatory fields
      properties <- properties %>% 
        drop_na(mag, place, time, updated, type, lon, lat, code)
   
      # # return list with prepared data
      # list(properties_df = properties, metadata_obj = metadata, bbox_obj = bbox)
      return(properties)

}

```

Column {.sidebar}
-----------------------------------------------------------------------

#### Daten Auswahl

```{r}

selectInput("data_choice",
            "Wählen Sie den Zeitraum der Erdbeben aus:",
            choices = c("24 Stunden", "7 Tage", "1 Monat"))

data_selected <- reactive({
  # update all 10 min
  invalidateLater(600000)
  
  switch(input$data_choice,
         "24 Stunden" = past_day,
         "7 Tage" = past_week,
         "1 Monat" = past_month)
})

```
Column {data-hight=800}
-----------------------------------------------------------------------
#### Erdbeben mit einer Magnitude grösser als 5

```{r}
output$map <- renderLeaflet({
  
  data_to_plot <- pipeline(data_selected())

  if(nrow(data_to_plot) == 0){
    leaflet() %>%
        addTiles() %>%
        addMarkers(lng = 0, lat = 0, popup = "Keine Daten vorhanden")
  } else {
  leaflet(data_to_plot) %>%
    addTiles() %>%
    addCircleMarkers(
      lat = ~lat,
      lng = ~lon,
      radius = ~mag *2,
      fillColor = ~colorNumeric("YlOrRd", mag)(mag),
      color = "#000000",
      weight = 1,
      opacity = 1,
      fillOpacity = 0.7,
      popup = ~paste("Ort:", place,
                     "<br>Datum:", time,
                     "<br>Magnitude:", round(mag, 4), 
                     "<br>Tiefe:", round(depth, 2))
    )
  }
})

leafletOutput("map")

```

